server:
  port: 8080
  servlet:
    context-path: /pdca

spring:
  datasource:
    url: jdbc:mysql://192.168.6.140:3306/pdca?useSSL=false&serverTimezone=UTC
    username: PDCA
    password: PMSzeFScEwikKFdE
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  mail:
    host: smtp.example.com
    port: 587
    username: your-email@example.com
    password: your-email-password

  # 初始用户配置
  init:
    user:
      admin:
        username: admin
        password: admin123
        email: admin@pdca.com
      test:
        username: test
        password: test123
        email: test@pdca.com
      manager:
        username: manager
        password: manager123
        email: manager@pdca.com

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    root: INFO
    com.example.pdca: DEBUG

swagger:
  enable: true

jwt:
  secret: pdcaProjectSecretKey
  expiration: 86400000  # 24小时

# 跨域配置
cors:
  allowed-origins: "*"
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS,HEAD,PATCH 