server:
  port: 8080
  servlet:
    context-path: /pdca

spring:
  datasource:
    # 使用H2内存数据库进行测试
    url: jdbc:h2:mem:pdca_test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop  # 测试环境每次重新创建表
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # 测试环境禁用邮件服务
  mail:
    host: localhost
    port: 3025
    username: test
    password: test

  # 测试用户配置
  init:
    user:
      enabled: true
      admin:
        username: admin
        password: admin123
        email: admin@test.com
      test:
        username: test
        password: test123
        email: test@test.com

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    root: INFO
    com.example.pdca: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

swagger:
  enable: true

jwt:
  secret: pdcaTestSecretKey
  expiration: 86400000

# 测试环境跨域配置
cors:
  allowed-origins: "*"
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS,HEAD,PATCH
  allowed-headers: "*"
  allow-credentials: true
  max-age: 3600

# 禁用缓存
cache:
  type: none

# 禁用安全配置
security:
  require-ssl: false 